/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as JaRouteImport } from './routes/ja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LokalRouteImport } from './routes/lokal'
import { Route as SchroniskoRouteImport } from './routes/schronisko'
import { Route as TablicaRouteImport } from './routes/tablica'
import { Route as WtyczkaRouteImport } from './routes/wtyczka'
import { Route as SpotSpotIdRouteImport } from './routes/spot.$spotId'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LokalRoute = LokalRouteImport.update({
  id: '/lokal',
  path: '/lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const SchroniskoRoute = SchroniskoRouteImport.update({
  id: '/schronisko',
  path: '/schronisko',
  getParentRoute: () => rootRouteImport,
} as any)
const TablicaRoute = TablicaRouteImport.update({
  id: '/tablica',
  path: '/tablica',
  getParentRoute: () => rootRouteImport,
} as any)
const WtyczkaRoute = WtyczkaRouteImport.update({
  id: '/wtyczka',
  path: '/wtyczka',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotSpotIdRoute = SpotSpotIdRouteImport.update({
  id: '/spot/$spotId',
  path: '/spot/$spotId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/ja': typeof JaRoute
  '/login': typeof LoginRoute
  '/lokal': typeof LokalRoute
  '/schronisko': typeof SchroniskoRoute
  '/tablica': typeof TablicaRoute
  '/wtyczka': typeof WtyczkaRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/ja': typeof JaRoute
  '/login': typeof LoginRoute
  '/lokal': typeof LokalRoute
  '/schronisko': typeof SchroniskoRoute
  '/tablica': typeof TablicaRoute
  '/wtyczka': typeof WtyczkaRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/ja': typeof JaRoute
  '/login': typeof LoginRoute
  '/lokal': typeof LokalRoute
  '/schronisko': typeof SchroniskoRoute
  '/tablica': typeof TablicaRoute
  '/wtyczka': typeof WtyczkaRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/ja'
    | '/login'
    | '/lokal'
    | '/schronisko'
    | '/tablica'
    | '/wtyczka'
    | '/spot/$spotId'
    | '/u/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/ja'
    | '/login'
    | '/lokal'
    | '/schronisko'
    | '/tablica'
    | '/wtyczka'
    | '/spot/$spotId'
    | '/u/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/ja'
    | '/login'
    | '/lokal'
    | '/schronisko'
    | '/tablica'
    | '/wtyczka'
    | '/spot/$spotId'
    | '/u/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  JaRoute: typeof JaRoute
  LoginRoute: typeof LoginRoute
  LokalRoute: typeof LokalRoute
  SchroniskoRoute: typeof SchroniskoRoute
  TablicaRoute: typeof TablicaRoute
  WtyczkaRoute: typeof WtyczkaRoute
  SpotSpotIdRoute: typeof SpotSpotIdRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokal': {
      id: '/lokal'
      path: '/lokal'
      fullPath: '/lokal'
      preLoaderRoute: typeof LokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schronisko': {
      id: '/schronisko'
      path: '/schronisko'
      fullPath: '/schronisko'
      preLoaderRoute: typeof SchroniskoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablica': {
      id: '/tablica'
      path: '/tablica'
      fullPath: '/tablica'
      preLoaderRoute: typeof TablicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wtyczka': {
      id: '/wtyczka'
      path: '/wtyczka'
      fullPath: '/wtyczka'
      preLoaderRoute: typeof WtyczkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot/$spotId': {
      id: '/spot/$spotId'
      path: '/spot/$spotId'
      fullPath: '/spot/$spotId'
      preLoaderRoute: typeof SpotSpotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  JaRoute: JaRoute,
  LoginRoute: LoginRoute,
  LokalRoute: LokalRoute,
  SchroniskoRoute: SchroniskoRoute,
  TablicaRoute: TablicaRoute,
  WtyczkaRoute: WtyczkaRoute,
  SpotSpotIdRoute: SpotSpotIdRoute,
  UUserIdRoute: UUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
